import styles from './Footer.module.scss';





function Footer() {
    return (
        <div className={`grid wide ${styles.footer}`}>
            <h1 className={styles.footerHeading}>SHOPTVU GÌ CŨNG CÓ, MUA HẾT Ở SHOPTVU</h1>
            <p>ShopTvu - ứng dụng mua sắm trực tuyến thú vị, tin cậy, an toàn và miễn phí! ShopTvu là nền tảng giao dịch trực tuyến hàng đầu ở Đông Nam Á, có trụ sở chính ở Singapore, đã có mặt ở khắp các khu vực Singapore, Malaysia, Indonesia, Thái Lan, Philippines, Đài Loan, Brazil, México, Colombia, & Chile. Với sự đảm bảo của ShopTvu, bạn sẽ mua hàng trực tuyến an tâm và nhanh chóng hơn bao giờ hết!</p>
            <h1 className={styles.footerHeading}>MUA SẮM VÀ BÁN HÀNG ONLINE ĐƠN GIẢN, NHANH CHÓNG VÀ AN TOÀN</h1>
            <p>Nếu bạn đang tìm kiếm một trang web để mua và bán hàng trực tuyến thì ShopTvu.vn là một sự lựa chọn tuyệt vời dành cho bạn. ShopTvu là trang thương mại điện tử cho phép người mua và người bán tương tác và trao đổi dễ dàng thông tin về sản phẩm và chương trình khuyến mãi của shop. Do đó, việc mua bán trên ShopTvu trở nên nhanh chóng và đơn giản hơn. Bạn có thể trò chuyện trực tiếp với nhà bán hàng để hỏi trực tiếp về mặt hàng cần mua. Còn nếu bạn muốn tìm mua những dòng sản phẩm chính hãng, uy tín, ShopTvu Mall chính là sự lựa chọn lí tưởng dành cho bạn. Để bạn có thể dễ dàng khi tìm hiểu và sử dụng sản phẩm, ShopTvu Blog - trang blog thông tin chính thức của ShopTvu - sẽ giúp bạn có thể tìm được cho mình các kiến thức về xu hướng thời trang, review công nghệ, mẹo làm đẹp, tin tức tiêu dùng và deal giá tốt bất ngờ.<br/>Đến với ShopTvu, cơ hội để trở thành một nhà bán hàng dễ dàng hơn bao giờ hết. Chỉ với vài thao tác trên ứng dụng, bạn đã có thể đăng bán ngay những sản phẩm của mình. Không những thế, các nhà bán hàng có thể tự tạo chương trình khuyến mãi trên ShopTvu để thu hút người mua với những sản phẩm có mức giá hấp dẫn. Khi đăng nhập tại ShopTvu Kênh người bán, bạn có thể dễ dàng phân loại sản phẩm, theo dõi đơn hàng, chăm sóc khách hàng và cập nhập ngay các hoạt động của shop.<br/>Bên cạnh đó, ShopTvu hợp tác với nhiều đơn vị vận chuyển uy tín trên thị trường như SPX,... nhằm cung cấp dịch vu giao nhận và vận chuyển tiện lợi cho cả khách hàng và người bán. Cùng với nhiều ưu đãi với chi phí giao hàng hợp lý, ShopTvu đảm bảo cho khách hàng trải nghiệm mua sắm thuận tiện nhất.</p>
            <h1 className={styles.footerHeading}> TẢI ỨNG DỤNG ShopTvu NGAY ĐỂ MUA BÁN ONLINE MỌI LÚC, MỌI NƠI </h1>
            <p>Ưu điểm của ứng dụng ShopTvu là cho phép bạn mua và bán hàng mọi lúc, mọi nơi. Bạn có thể tải ứng dụng ShopTvu cũng như đăng sản phẩm bán hàng một cách nhanh chóng và tiện lợi. Ngoài ra, ứng dụng ShopTvu còn có những ưu điểm sau:

                Giao diện thân thiện, đơn giản, dễ sử dụng. Bạn sẽ dễ dàng thấy được ngay những sản phẩm nổi bật cũng như dễ dàng tìm đến các ô tìm kiếm, giỏ hàng hoặc tính năng chat liền tay, liên hệ tổng đài ShopTvu tiện lợi.
                Ứng dụng tích hợp công nghệ quản lý đơn mua và bán hàng tiện lợi trên cùng một tài khoản. Bạn sẽ vừa là người mua hàng, vừa là người bán hàng rất linh hoạt, dễ dàng.
                Cập nhập thông tin khuyến mãi, ShopTvu Flash Sale nhanh chóng và liên tục.
                Tại ShopTvu, bạn có thể lưu các mã giảm giá, Voucher Xtra và mã miễn phí vận chuyển toàn quốc. Bên cạnh đó, ShopTvu cũng sẽ có những chiến dịch khuyến mãi lớn hằng năm như Sale Tết, Sale Năm Mới, Sale 3.3, Sale 4.4, Sale 5.5, Sale 6.6, Sale 7.7, Sale 8.8, Sale 9.9, Sale 10.10, Sale 11.11, Sale Sinh Nhật 12.12; Khuyến Mãi Tết thả ga săn sale quà Tết chất lượng. Đây là thời điểm để người mua hàng có thể nhanh tay chọn ngay cho mình những mặt hàng ưa thích với mức giá giảm kỉ lục. Ngoài ra, bạn còn có thể thỏa thích săn sale vào các ngày trong tháng như Sale giữa tháng và Sale cuối tháng đón lương về, hoặc đón xem ShopTvu Live để săn hàng ngàn deal hời giá sốc. </p>
            <h1 className={styles.footerHeading}>MUA HÀNG HIỆU CAO CẤP GIÁ TỐT TẠI ShopTvu </h1>
            <p>Bên cạnh ShopTvu Premium, ShopTvu còn có rất nhiều khuyến mãi khủng cho hàng hiệu giảm đến 50%. Cộng với mã giao hàng miễn phí, ShopTvu cũng có các mã giảm giá được phân phối mỗi tháng từ rất nhiều gian hàng chính hãng tham gia chương trình khuyến mãi này. Bên cạnh đó, ShopTvu còn tập hợp rất nhiều thương hiệu đình đám được các nhà bán lẻ uy tín phân phối bán trên ShopTvu, top sản phẩm hot deal cho bạn săn sale luôn cập nhật mỗi giờ, mỗi ngày, đem đến cho bạn sự lựa chọn đa dạng, từ các hãng mỹ phẩm nổi tiếng hàng đầu như Kiehl's, MAC, Foreo, SK-II, Estee Lauder,... Đến những thương hiệu công nghệ nổi tiếng như: camera hành trình Gopro, máy ảnh Fuifilm, webcam Hikvision, máy đọc sách Kindle,... Tại ShopTvu, bạn có thể dễ dàng tìm thấy các thương hiệu giày thể thao phổ biến hiện nay như: New Balance, Nike, Vans, Crocs,...  </p>
            <h1 className={styles.footerHeading}>MUA HÀNG CHÍNH HÃNG TỪ CÁC THƯƠNG HIỆU LỚN VỚI ShopTvu</h1>
            <p>Mua hàng trên ShopTvu luôn là một trải nghiệm ấn tượng. Dù bạn đang có nhu cầu mua bất kỳ mặt hàng thời trang nam, thời trang nữ, đồng hồ, điện thoại, máy tính & laptop,... cho bản thân hay đang cần mua quà tặng doanh nghiệp tiện lợi như thẻ quà tặng ShopTvuGifts, ShopTvu cũng sẽ đảm bảo cung cấp cho bạn những sản phẩm ưng ý. Bên cạnh đó, ShopTvu cũng có sự tham gia của các thương hiệu hàng đầu thế giới ở đa dạng nhiều lĩnh vực khác nhau. Trong đó có thể kể đến Samsung, OPPO, Xiaomi, Innisfree, Unilever, P&G, Biti’s,...Các thương hiệu này hiện cũng đã có cửa hàng chính thức trên ShopTvu Mall với hàng trăm mặt hàng chính hãng, được cập nhập liên tục. Là một kênh bán hàng uy tín, ShopTvu luôn cam kết mang lại cho khách hàng những trải nghiệm mua sắm online giá rẻ, an toàn và tin cậy. Mọi thông tin về người bán và người mua đều được bảo mật tuyệt đối. Các hoạt động giao dịch thanh toán tại ShopTvu luôn được đảm bảo diễn ra nhanh chóng, an toàn. Một vấn đề nữa khiến cho các khách hàng luôn quan tâm đó chính là mua hàng trên ShopTvu có đảm bảo không.<br/>ShopTvu luôn cam kết mọi sản phẩm trên ShopTvu, đặc biệt là ShopTvu Mall đều là những sản phẩm chính hãng, đầy đủ tem nhãn, bảo hành từ nhà bán hàng. Ngoài ra, ShopTvu bảo vệ người mua và người bán bằng cách giữ số tiền giao dịch đến khi người mua xác nhận đồng ý với đơn hàng và không có yêu cầu khiếu nại, trả hàng hay hoàn tiền nào. Thanh toán sau đó sẽ được chuyển đến cho người bán. Đến với ShopTvu ngay hôm nay để mua hàng online giá rẻ và trải nghiệm dịch vụ chăm sóc khách hàng tuyệt vời tại đây. Đặc biệt khi mua sắm trên ShopTvu Mall, bạn sẽ được miễn phí vận chuyển, giao hàng tận nơi và 15 ngày miễn phí trả hàng. Ngoài ra, khách hàng có thể sử dụng ShopTvu Xu để đổi lấy mã giảm giá có giá trị cao và voucher dịch vụ hấp dẫn. Tiếp đến là ShopTvu Live, ShopTvu Video, ShopTvu Home Club, ShopTvu Mum Club, ShopTvu Beauty Club và ShopTvu Book Club với các ưu đãi độc quyền từ các thương hiệu lớn có những khách hàng đã đăng ký làm thành viên. Hãy truy cập ngay ShopTvu Việt Nam hoặc tải ngay ứng dụng ShopTvu về điện thoại ngay hôm nay! </p>
        </div>
    );
}
export default Footer;